[
  // --- หมวดที่ 1: ความสามารถทั่วไป (ข้อ 1-30) ---
  { "id": 1, "category": "ความสามารถทั่วไป", "question": "อนุกรม: 3, 6, 12, 24, ... ตัวเลขถัดไปคือข้อใด?", "options": ["36", "42", "48", "54"], "answerIndex": 2, "explanation": "\"ตอบ 48 ครับ เพราะชุดนี้เพิ่มขึ้นแบบคูณ 2 ไปเรื่อยๆ (24 x 2 = 48) ครับ\"" },
  { "id": 2, "category": "ความสามารถทั่วไป", "question": "อุปมาอุปไมย: นก : บิน :: ปลา : ?", "options": ["เดิน", "กระโดด", "ว่ายน้ำ", "เลื้อย"], "answerIndex": 2, "explanation": "\"ตอบ ว่ายน้ำ ครับ เพราะเป็นการเปรียบเทียบสัตว์กับวิธีการเคลื่อนที่ครับ\"" },
  { "id": 3, "category": "ความสามารถทั่วไป", "question": "ค่าเฉลี่ยของ 10, 20, 30, 40, 50 คือเท่าใด?", "options": ["25", "30", "35", "40"], "answerIndex": 1, "explanation": "\"ตอบ 30 ครับ เพราะผลรวมคือ 150 หารด้วย 5 ตัว ได้ 30 พอดีครับ\"" },
  { "id": 4, "category": "ความสามารถทั่วไป", "question": "รถวิ่งด้วยความเร็ว 60 กม./ชม. ในเวลา 4 ชม. จะได้ระยะทางเท่าใด?", "options": ["200", "220", "240", "260"], "answerIndex": 2, "explanation": "\"ตอบ 240 ครับ คิดจากความเร็วคูณเวลา (60 x 4 = 240) ครับ\"" },
  { "id": 5, "category": "ความสามารถทั่วไป", "question": "30% ของ 800 มีค่าเท่ากับข้อใด?", "options": ["210", "240", "270", "300"], "answerIndex": 1, "explanation": "\"ตอบ 240 ครับ คิดจาก (30/100) x 800 = 240 ครับ\"" },
  { "id": 6, "category": "ความสามารถทั่วไป", "question": "อนุกรม: 1, 3, 7, 15, ... ตัวถัดไปคือ?", "options": ["25", "30", "31", "32"], "answerIndex": 2, "explanation": "\"ตอบ 31 ครับ สูตรคือ (ตัวหน้า x 2) + 1 จะได้ 15 x 2 = 30 แล้วบวก 1 ครับ\"" },
  { "id": 7, "category": "ความสามารถทั่วไป", "question": "ถ้าไข่ 10 ฟอง ราคา 50 บาท ไข่ 30 ฟอง จะราคาเท่าไหร่?", "options": ["100", "120", "150", "200"], "answerIndex": 2, "explanation": "\"ตอบ 150 ครับ เพราะตกฟองละ 5 บาท 30 x 5 = 150 ครับ\"" },
  { "id": 8, "category": "ความสามารถทั่วไป", "question": "สี่เหลี่ยมจัตุรัสมีด้านยาว 6 ซม. จะมีพื้นที่กี่ตารางซม.?", "options": ["12", "24", "36", "48"], "answerIndex": 2, "explanation": "\"ตอบ 36 ครับ สูตรคือ ด้าน x ด้าน (6 x 6 = 36) ครับ\"" },
  { "id": 9, "category": "ความสามารถทั่วไป", "question": "เลขชุดใดต่างจากพวก?", "options": ["15", "25", "35", "42"], "answerIndex": 3, "explanation": "\"ตอบ 42 ครับ เพราะตัวอื่นหารด้วย 5 ลงตัวทั้งหมดครับ\"" },
  { "id": 10, "category": "ความสามารถทั่วไป", "question": "ซื้อของ 1,000 บาท ลด 20% ต้องจ่ายกี่บาท?", "options": ["700", "800", "900", "950"], "answerIndex": 1, "explanation": "\"ตอบ 800 ครับ ลดไป 200 บาท (1,000 - 200 = 800) ครับ\"" },
  { "id": 11, "category": "ความสามารถทั่วไป", "question": "ห.ร.ม. ของ 8 และ 12 คือ?", "options": ["2", "4", "8", "24"], "answerIndex": 1, "explanation": "\"ตอบ 4 ครับ เพราะเป็นตัวเลขที่มากที่สุดที่หารทั้ง 8 และ 12 ลงตัวครับ\"" },
  { "id": 12, "category": "ความสามารถทั่วไป", "question": "ค.ร.น. ของ 3 และ 5 คือ?", "options": ["8", "10", "15", "30"], "answerIndex": 2, "explanation": "\"ตอบ 15 ครับ เพราะเป็นเลขน้อยที่สุดที่ทั้ง 3 และ 5 หารลงตัวครับ\"" },
  { "id": 13, "category": "ความสามารถทั่วไป", "question": "มุมภายในของรูปสี่เหลี่ยมรวมกันได้กี่องศา?", "options": ["180", "270", "360", "540"], "answerIndex": 2, "explanation": "\"ตอบ 360 องศาครับ\"" },
  { "id": 14, "category": "ความสามารถทั่วไป", "question": "เงิน 500 บาท แบ่งให้ ก และ ข ในอัตราส่วน 2:3 ข จะได้กี่บาท?", "options": ["200", "250", "300", "350"], "answerIndex": 2, "explanation": "\"ตอบ 300 ครับ รวมเป็น 5 ส่วน (ส่วนละ 100) ข ได้ 3 ส่วน คือ 300 ครับ\"" },
  { "id": 15, "category": "ความสามารถทั่วไป", "question": "รากที่สองของ 144 คือ?", "options": ["10", "12", "14", "16"], "answerIndex": 1, "explanation": "\"ตอบ 12 ครับ เพราะ 12 x 12 = 144 ครับ\"" },
  { "id": 16, "category": "ความสามารถทั่วไป", "question": "ทอดลูกเต๋า 1 ลูก โอกาสได้เลขที่มากกว่า 4 เป็นเท่าใด?", "options": ["1/6", "2/6", "3/6", "4/6"], "answerIndex": 1, "explanation": "\"ตอบ 2/6 (หรือ 1/3) ครับ เพราะมีเลข 5 กับ 6 รวม 2 หน้าครับ\"" },
  { "id": 17, "category": "ความสามารถทั่วไป", "question": "อนุกรม: 100, 90, 80, 70, ... ตัวถัดไปคือ?", "options": ["50", "60", "65", "55"], "answerIndex": 1, "explanation": "\"ตอบ 60 ครับ เพราะลดลงทีละ 10 เท่าๆ กันครับ\"" },
  { "id": 18, "category": "ความสามารถทั่วไป", "question": "ไก่อยู่ในกรง มีขาไก่รวมกัน 20 ขา มีไก่กี่ตัว?", "options": ["5", "10", "15", "20"], "answerIndex": 1, "explanation": "\"ตอบ 10 ตัว ครับ เพราะไก่ 1 ตัวมี 2 ขา (20 / 2 = 10)\"" },
  { "id": 19, "category": "ความสามารถทั่วไป", "question": "วันนี้วันศุกร์ อีก 15 วันจะเป็นวันอะไร?", "options": ["ศุกร์", "เสาร์", "อาทิตย์", "จันทร์"], "answerIndex": 1, "explanation": "\"ตอบ เสาร์ ครับ 15 หาร 7 เหลือเศษ 1 นับเพิ่มจากวันศุกร์ไป 1 วันครับ\"" },
  { "id": 20, "category": "ความสามารถทั่วไป", "question": "มุมแหลมคือมุมที่มีขนาดเท่าใด?", "options": ["90 องศา", "มากกว่า 90", "น้อยกว่า 90", "180 องศา"], "answerIndex": 2, "explanation": "\"ตอบ น้อยกว่า 90 องศาครับ\"" },
  { "id": 21, "category": "ความสามารถทั่วไป", "question": "อนุกรม: 1, 8, 27, 64, ... ตัวถัดไปคือ?", "options": ["81", "100", "125", "150"], "answerIndex": 2, "explanation": "\"ตอบ 125 ครับ เพราะเป็นเลขยกกำลังสาม (5x5x5 = 125)\"" },
  { "id": 22, "category": "ความสามารถทั่วไป", "question": "อุปมาอุปไมย: เช้า : สาย :: ? : ?", "options": ["เด็ก : ผู้ใหญ่", "มืด : สว่าง", "ร้อน : หนาว", "เดิน : วิ่ง"], "answerIndex": 0, "explanation": "\"ตอบ เด็ก : ผู้ใหญ่ ครับ เพราะเป็นความสัมพันธ์เชิงลำดับเวลาหรือวัยครับ\"" },
  { "id": 23, "category": "ความสามารถทั่วไป", "question": "1-50 มีเลข 5 ทั้งหมดกี่ตัว?", "options": ["5", "6", "10", "15"], "answerIndex": 1, "explanation": "\"ตอบ 6 ตัว ครับ (5, 15, 25, 35, 45 และ 50)\"" },
  { "id": 24, "category": "ความสามารถทั่วไป", "question": "สุ่มหยิบไพ่ 1 ใบจากสำรับ โอกาสได้โพดำคือ?", "options": ["1/2", "1/4", "1/13", "1/52"], "answerIndex": 1, "explanation": "\"ตอบ 1/4 ครับ เพราะมี 4 ดอกเท่าๆ กันในสำรับครับ\"" },
  { "id": 25, "category": "ความสามารถทั่วไป", "question": "สี่เหลี่ยมผืนผ้ากว้าง 4 ยาว 6 พื้นที่คือเท่าใด?", "options": ["10", "20", "24", "28"], "answerIndex": 2, "explanation": "\"ตอบ 24 ครับ กว้าง x ยาว (4 x 6 = 24)\"" },
  { "id": 26, "category": "ความสามารถทั่วไป", "question": "น้ำ 1 ลิตร เท่ากับกี่ลูกบาศก์เซนติเมตร (cc)?", "options": ["100", "500", "1,000", "10,000"], "answerIndex": 2, "explanation": "\"ตอบ 1,000 ครับ\"" },
  { "id": 27, "category": "ความสามารถทั่วไป", "question": "อนุกรม: 1/3, 1/9, 1/27, ... ตัวถัดไปคือ?", "options": ["1/30", "1/54", "1/81", "1/90"], "answerIndex": 2, "explanation": "\"ตอบ 1/81 ครับ ส่วนคูณ 3 ไปเรื่อยๆ\"" },
  { "id": 28, "category": "ความสามารถทั่วไป", "question": "ถ้า 3x - 4 = 11 แล้ว x คือเท่าใด?", "options": ["3", "4", "5", "6"], "answerIndex": 2, "explanation": "\"ตอบ 5 ครับ 3x = 15 ดังนั้น x = 5\"" },
  { "id": 29, "category": "ความสามารถทั่วไป", "question": "เลขใดไม่ใช่จำนวนเฉพาะ?", "options": ["2", "3", "7", "9"], "answerIndex": 3, "explanation": "\"ตอบ 9 ครับ เพราะ 3 หารลงตัว\"" },
  { "id": 30, "category": "ความสามารถทั่วไป", "question": "0.1 x 0.1 มีค่าเท่าใด?", "options": ["0.1", "0.01", "1.1", "0.2"], "answerIndex": 1, "explanation": "\"ตอบ 0.01 ครับ ทศนิยมสองตำแหน่ง\"" },

  // --- หมวดที่ 2: ภาษาไทย (ข้อ 31-55) ---
  { "id": 31, "category": "ภาษาไทย", "question": "ข้อใดสะกด 'กะเพรา' ได้ถูกต้อง?", "options": ["กระเพรา", "กะเพรา", "กะเพลา", "กระเพลา"], "answerIndex": 1, "explanation": "\"ตอบ กะเพรา ครับ ไม่มี ร เรือที่ กะ\"" },
  { "id": 32, "category": "ภาษาไทย", "question": "ข้อใดสะกด 'ไอศกรีม' ได้ถูกต้อง?", "options": ["ไอศครีม", "ไอศกรีม", "ไอศกรีมม์", "ไอศครีมม์"], "answerIndex": 1, "explanation": "\"ตอบ ไอศกรีม ใช้ ก ไก่ ครับ\"" },
  { "id": 33, "category": "ภาษาไทย", "question": "ลักษณนามของ 'พระพุทธรูป' คือ?", "options": ["องค์", "รูป", "ตน", "ใบ"], "answerIndex": 0, "explanation": "\"ตอบ องค์ ครับ ถ้าพระสงฆ์ถึงจะใช้ รูป\"" },
  { "id": 34, "category": "ภาษาไทย", "question": "ข้อใดเป็นคำสมาสที่มีการสนธิ?", "options": ["พลความ", "วิทยาศาสตร์", "ธันวาคม", "ราชการ"], "answerIndex": 2, "explanation": "\"ตอบ ธันวาคม (ธนู + อาคม) ครับ\"" },
  { "id": 35, "category": "ภาษาไทย", "question": "สำนวน 'ชุบมือเปิบ' หมายถึงอะไร?", "options": ["ล้างมือสะอาด", "แย่งผลประโยชน์คนอื่น", "ขยันทำงาน", "กินข้าวอร่อย"], "answerIndex": 1, "explanation": "\"ตอบ แย่งเอาผลประโยชน์จากคนอื่นโดยที่ตัวเองไม่ได้ลงแรงครับ\"" },
  { "id": 36, "category": "ภาษาไทย", "question": "คำราชาศัพท์ของ 'ตาย' สำหรับพระมหากษัตริย์?", "options": ["มรณภาพ", "ถึงแก่กรรม", "สวรรคต", "สิ้นชีพิตักษัย"], "answerIndex": 2, "explanation": "\"ตอบ สวรรคต ครับ\"" },
  { "id": 37, "category": "ภาษาไทย", "question": "ข้อใดเป็นประโยคความรวม?", "options": ["นกบิน", "พ่อและแม่ไปตลาด", "น้องนอนหลับ", "พี่กินข้าว"], "answerIndex": 1, "explanation": "\"ตอบ พ่อและแม่ไปตลาด เพราะมีคำว่า 'และ' เชื่อมครับ\"" },
  { "id": 38, "category": "ภาษาไทย", "question": "ข้อใดมาจากภาษาจีน?", "options": ["ฟุตบอล", "ปิ่นโต", "ก๋วยเตี๋ยว", "เทคโนโลยี"], "answerIndex": 2, "explanation": "\"ตอบ ก๋วยเตี๋ยว ครับ\"" },
  { "id": 39, "category": "ภาษาไทย", "question": "คำตรงข้ามของ 'สงบ'?", "options": ["นิ่ง", "วุ่นวาย", "เรียบร้อย", "เงียบ"], "answerIndex": 1, "explanation": "\"ตอบ วุ่นวาย ครับ\"" },
  { "id": 40, "category": "ภาษาไทย", "question": "ข้อใดสะกดถูกต้อง?", "options": ["บรรยากาศ", "บันยากาศ", "บรยากาศ", "บรรญาการ"], "answerIndex": 0, "explanation": "\"ตอบ บรรยากาศ ใช้ บรร- ครับ\"" },
  { "id": 41, "category": "ภาษาไทย", "question": "ข้อใดใช้ 'บัน' ผิด?", "options": ["บันทึก", "บันเทิง", "บันได", "บันยาย"], "answerIndex": 3, "explanation": "\"ตอบ บันยาย ผิด ต้องใช้ บรรยาย ครับ\"" },
  { "id": 42, "category": "ภาษาไทย", "question": "ลักษณนามของ 'แหวน'?", "options": ["อัน", "วง", "ชิ้น", "เล่ม"], "answerIndex": 1, "explanation": "\"ตอบ วง ครับ\"" },
  { "id": 43, "category": "ภาษาไทย", "question": "คำว่า 'พินิจ' สะกดอย่างไร?", "options": ["พินิช", "พินิจ", "พินิศ", "พินิษฐ์"], "answerIndex": 1, "explanation": "\"ตอบ พินิจ ใช้ จ จาน ครับ\"" },
  { "id": 44, "category": "ภาษาไทย", "question": "ข้อใดเป็นคำอุทานเสริมบท?", "options": ["อุ๊ย!", "โธ่!", "หนังสือหนังหา", "ไชโย!"], "answerIndex": 2, "explanation": "\"ตอบ หนังสือหนังหา ครับ\"" },
  { "id": 45, "category": "ภาษาไทย", "question": "ข้อใดเป็นคำกริยา?", "options": ["กระโดด", "คน", "แมว", "ดี"], "answerIndex": 0, "explanation": "\"ตอบ กระโดด ครับ\"" },
  { "id": 46, "category": "ภาษาไทย", "question": "คำว่า 'ปรารถนา' อ่านอย่างไร?", "options": ["ปราด-ถะ-หนา", "ปะ-หราด-ถะ-หนา", "ปราด-นา", "ปะ-ราด-ถะ-นา"], "answerIndex": 0, "explanation": "\"ตอบ ปราด-ถะ-หนา ครับ\"" },
  { "id": 47, "category": "ภาษาไทย", "question": "ความหมายของ 'ปากเปียกปากแฉะ'?", "options": ["หิวข้าว", "พร่ำสอนซ้ำๆ", "พูดเก่ง", "น้ำลายไหล"], "answerIndex": 1, "explanation": "\"ตอบ การว่ากล่าวตักเตือนซ้ำแล้วซ้ำเล่าครับ\"" },
  { "id": 48, "category": "ภาษาไทย", "question": "คำสุภาพของ 'วัว' คือ?", "options": ["กระบือ", "พยัคฆ์", "คาวี", "กุญชร"], "answerIndex": 2, "explanation": "\"ตอบ คาวี (หรือ โค) ครับ\"" },
  { "id": 49, "category": "ภาษาไทย", "question": "ข้อใดเป็นคำควบไม่แท้?", "options": ["กวาด", "พริก", "ทราย", "ใกล้"], "answerIndex": 2, "explanation": "\"ตอบ ทราย ออกเสียงเป็น ซ ครับ\"" },
  { "id": 50, "category": "ภาษาไทย", "question": "คำว่า 'โน้ตเพลง' อ่านอย่างไร?", "options": ["โนด-เป-ลา", "โน้ต-เป-ลา", "โนด-เป-ลา-โน", "โน้ด-ปะ-ลา"], "answerIndex": 1, "explanation": "\"ตอบ โน้ต-เป-ลา ครับ\"" },
  { "id": 51, "category": "ภาษาไทย", "question": "คำพ้องเสียงของ 'กาล' คือ?", "options": ["กาน", "การ", "กำ", "กาม"], "answerIndex": 1, "explanation": "\"ตอบ การ ครับ ออกเสียงเหมือนกันความหมายต่างกัน\"" },
  { "id": 52, "category": "ภาษาไทย", "question": "ตรงข้ามกับ 'มืด'?", "options": ["ดำ", "สว่าง", "เงียบ", "หนาว"], "answerIndex": 1, "explanation": "\"ตอบ สว่าง ครับ\"" },
  { "id": 53, "category": "ภาษาไทย", "question": "ข้อใดเป็นคำประสม?", "options": ["นกยูง", "น้ำแข็ง", "มะลิ", "กะปิ"], "answerIndex": 1, "explanation": "\"ตอบ น้ำแข็ง (น้ำ+แข็ง) ครับ\"" },
  { "id": 54, "category": "ภาษาไทย", "question": "โวหารเล่าเรื่องตามลำดับ?", "options": ["บรรยาย", "พรรณนา", "เทศนา", "อุปมา"], "answerIndex": 0, "explanation": "\"ตอบ บรรยายโวหาร ครับ\"" },
  { "id": 55, "category": "ภาษาไทย", "question": "คำราชาศัพท์ของ 'หัว'?", "options": ["พระนลาฏ", "พระกรรณ", "พระเศียร", "พระโอษฐ์"], "answerIndex": 2, "explanation": "\"ตอบ พระเศียร ครับ\"" },

  // --- หมวดที่ 3: ภาษาอังกฤษ (ข้อ 56-85) ---
  { "id": 56, "category": "ภาษาอังกฤษ", "question": "Plural of 'Mouse'?", "options": ["Mouses", "Mice", "Mices", "Mousie"], "answerIndex": 1, "explanation": "\"ตอบ Mice ครับ\"" },
  { "id": 57, "category": "ภาษาอังกฤษ", "question": "I _____ a movie last night.", "options": ["watch", "watches", "watched", "watching"], "answerIndex": 2, "explanation": "\"ตอบ watched ช่อง 2 บอกอดีตครับ\"" },
  { "id": 58, "category": "ภาษาอังกฤษ", "question": "This bag is _____ than that one.", "options": ["expensive", "more expensive", "expensiver", "most expensive"], "answerIndex": 1, "explanation": "\"ตอบ more expensive ขั้นกว่าครับ\"" },
  { "id": 59, "category": "ภาษาอังกฤษ", "question": "_____ is your birthday?", "options": ["Where", "When", "What", "Who"], "answerIndex": 1, "explanation": "\"ตอบ When ถามเมื่อไหร่ครับ\"" },
  { "id": 60, "category": "ภาษาอังกฤษ", "question": "They _____ students.", "options": ["is", "am", "are", "be"], "answerIndex": 2, "explanation": "\"ตอบ are ใช้กับประธานพหูพจน์ครับ\"" },
  { "id": 61, "category": "ภาษาอังกฤษ", "question": "Look! It _____.", "options": ["rain", "rains", "is raining", "rained"], "answerIndex": 2, "explanation": "\"ตอบ is raining กำลังเกิดขึ้นครับ\"" },
  { "id": 62, "category": "ภาษาอังกฤษ", "question": "She wants _____ umbrella.", "options": ["a", "an", "the", "some"], "answerIndex": 1, "explanation": "\"ตอบ an นำหน้าเสียงสระครับ\"" },
  { "id": 63, "category": "ภาษาอังกฤษ", "question": "We _____ English every day.", "options": ["study", "studies", "studying", "studied"], "answerIndex": 0, "explanation": "\"ตอบ study ประธานพหูพจน์ช่อง 1 ครับ\"" },
  { "id": 64, "category": "ภาษาอังกฤษ", "question": "He _____ to the gym on Mondays.", "options": ["go", "goes", "going", "gone"], "answerIndex": 1, "explanation": "\"ตอบ goes ประธานเอกพจน์ต้องเติม es ครับ\"" },
  { "id": 65, "category": "ภาษาอังกฤษ", "question": "Give it to _____.", "options": ["he", "his", "him", "himself"], "answerIndex": 2, "explanation": "\"ตอบ him เป็นกรรมครับ\"" },
  { "id": 66, "category": "ภาษาอังกฤษ", "question": "Which one is a vegetable?", "options": ["Apple", "Banana", "Broccoli", "Grape"], "answerIndex": 2, "explanation": "\"ตอบ Broccoli เป็นผักครับ\"" },
  { "id": 67, "category": "ภาษาอังกฤษ", "question": "He is good _____ football.", "options": ["in", "on", "at", "with"], "answerIndex": 2, "explanation": "\"ตอบ at ใช้คู่กับ good ครับ\"" },
  { "id": 68, "category": "ภาษาอังกฤษ", "question": "How _____ brothers do you have?", "options": ["much", "many", "old", "long"], "answerIndex": 1, "explanation": "\"ตอบ many ใช้กับนามนับได้พหูพจน์ครับ\"" },
  { "id": 69, "category": "ภาษาอังกฤษ", "question": "You _____ wear a seatbelt.", "options": ["can", "should", "might", "may"], "answerIndex": 1, "explanation": "\"ตอบ should ควรทำ (คำแนะนำ) ครับ\"" },
  { "id": 70, "category": "ภาษาอังกฤษ", "question": "Today is Friday. Tomorrow is _____.", "options": ["Saturday", "Sunday", "Monday", "Tuesday"], "answerIndex": 0, "explanation": "\"ตอบ Saturday ครับ\"" },
  { "id": 71, "category": "ภาษาอังกฤษ", "question": "The book is _____ the table.", "options": ["on", "in", "at", "under of"], "answerIndex": 0, "explanation": "\"ตอบ on บนครับ\"" },
  { "id": 72, "category": "ภาษาอังกฤษ", "question": "_____ color do you like?", "options": ["Who", "What", "When", "Where"], "answerIndex": 1, "explanation": "\"ตอบ What ครับ\"" },
  { "id": 73, "category": "ภาษาอังกฤษ", "question": "I _____ happy today.", "options": ["is", "am", "are", "be"], "answerIndex": 1, "explanation": "\"ตอบ am ใช้กับ I ครับ\"" },
  { "id": 74, "category": "ภาษาอังกฤษ", "question": "Would you like _____ coffee?", "options": ["a", "an", "some", "any"], "answerIndex": 2, "explanation": "\"ตอบ some ใช้ในการเสนอครับ\"" },
  { "id": 75, "category": "ภาษาอังกฤษ", "question": "Mount Everest is the _____ mountain.", "options": ["high", "higher", "highest", "more high"], "answerIndex": 2, "explanation": "\"ตอบ highest ขั้นสูงสุดครับ\"" },
  { "id": 76, "category": "ภาษาอังกฤษ", "question": "It is _____ (มีหิมะตก).", "options": ["sunny", "windy", "snowy", "rainy"], "answerIndex": 2, "explanation": "\"ตอบ snowy ครับ\"" },
  { "id": 77, "category": "ภาษาอังกฤษ", "question": "Who helps sick people?", "options": ["Driver", "Cook", "Doctor", "Pilot"], "answerIndex": 2, "explanation": "\"ตอบ Doctor ครับ\"" },
  { "id": 78, "category": "ภาษาอังกฤษ", "question": "I don't have _____ pencils.", "options": ["some", "any", "a", "an"], "answerIndex": 1, "explanation": "\"ตอบ any ในประโยคปฏิเสธครับ\"" },
  { "id": 79, "category": "ภาษาอังกฤษ", "question": "Does she like tea? - Yes, she _____.", "options": ["do", "does", "is", "likes"], "answerIndex": 1, "explanation": "\"ตอบ does ถาม Does ตอบ does ครับ\"" },
  { "id": 80, "category": "ภาษาอังกฤษ", "question": "Opposite of 'Hard'?", "options": ["Easy", "Difficult", "Strong", "Tall"], "answerIndex": 0, "explanation": "\"ตอบ Easy ครับ\"" },
  { "id": 81, "category": "ภาษาอังกฤษ", "question": "_____ are you? - I am 20 years old.", "options": ["How old", "How many", "What", "Who"], "answerIndex": 0, "explanation": "\"ตอบ How old ถามอายุครับ\"" },
  { "id": 82, "category": "ภาษาอังกฤษ", "question": "I _____ my homework at 8 PM.", "options": ["do", "did", "done", "doing"], "answerIndex": 1, "explanation": "\"ตอบ did บอกอดีตครับ\"" },
  { "id": 83, "category": "ภาษาอังกฤษ", "question": "Please _____ quiet.", "options": ["be", "is", "am", "are"], "answerIndex": 0, "explanation": "\"ตอบ be ครับ\"" },
  { "id": 84, "category": "ภาษาอังกฤษ", "question": "I have lived here _____ 2010.", "options": ["for", "since", "at", "in"], "answerIndex": 1, "explanation": "\"ตอบ since บอกจุดเริ่มต้นเวลาครับ\"" },
  { "id": 85, "category": "ภาษาอังกฤษ", "question": "This is _____ book. (ของฉัน)", "options": ["my", "mine", "I", "me"], "answerIndex": 0, "explanation": "\"ตอบ my ครับ\"" },

  // --- หมวดที่ 4: เทคโนโลยีสารสนเทศ (ข้อ 86-110) ---
  { "id": 86, "category": "เทคโนโลยีสารสนเทศ", "question": "ROM ย่อมาจากอะไร?", "options": ["Read Only Memory", "Random Only Memory", "Run On Memory", "Real Online Memory"], "answerIndex": 0, "explanation": "\"ตอบ Read Only Memory ครับ\"" },
  { "id": 87, "category": "เทคโนโลยีสารสนเทศ", "question": "หน่วยเก็บข้อมูลที่เล็กที่สุดคือ?", "options": ["Bit", "Byte", "KB", "MB"], "answerIndex": 0, "explanation": "\"ตอบ Bit (บิต) ครับ\"" },
  { "id": 88, "category": "เทคโนโลยีสารสนเทศ", "question": "Ctrl + C คือคำสั่งใด?", "options": ["Paste", "Cut", "Copy", "Undo"], "answerIndex": 2, "explanation": "\"ตอบ Copy ครับ\"" },
  { "id": 89, "category": "เทคโนโลยีสารสนเทศ", "question": ".ac.th คือหน่วยงานใด?", "options": ["รัฐบาล", "เอกชน", "สถานศึกษา", "มูลนิธิ"], "answerIndex": 2, "explanation": "\"ตอบ สถานศึกษา ครับ\"" },
  { "id": 90, "category": "เทคโนโลยีสารสนเทศ", "question": "ใช้ทำตารางคำนวณคือซอฟต์แวร์ใด?", "options": ["Word", "Excel", "PowerPoint", "Access"], "answerIndex": 1, "explanation": "\"ตอบ Excel ครับ\"" },
  { "id": 91, "category": "เทคโนโลยีสารสนเทศ", "question": "ข้อใดเป็นระบบปฏิบัติการมือถือ?", "options": ["Windows", "Android", "Office", "Chrome"], "answerIndex": 1, "explanation": "\"ตอบ Android ครับ\"" },
  { "id": 92, "category": "เทคโนโลยีสารสนเทศ", "question": "Firewall มีไว้เพื่ออะไร?", "options": ["เพิ่มความเร็ว", "ป้องกันการบุกรุก", "พ่นไฟ", "ประหยัดไฟ"], "answerIndex": 1, "explanation": "\"ตอบ ป้องกันการบุกรุกเครือข่ายครับ\"" },
  { "id": 93, "category": "เทคโนโลยีสารสนเทศ", "question": "อุปกรณ์ใดทำหน้าที่แสดงผล?", "options": ["Monitor", "Keyboard", "Mouse", "Scanner"], "answerIndex": 0, "explanation": "\"ตอบ Monitor ครับ\"" },
  { "id": 94, "category": "เทคโนโลยีสารสนเทศ", "question": "1 TB ประมาณกี่ GB?", "options": ["100", "500", "1,000", "10,000"], "answerIndex": 2, "explanation": "\"ตอบ 1,000 GB ครับ\"" },
  { "id": 95, "category": "เทคโนโลยีสารสนเทศ", "question": "Bluetooth เป็นการเชื่อมต่อระยะใด?", "options": ["สั้น", "ไกล", "ทั่วโลก", "ข้ามจังหวัด"], "answerIndex": 0, "explanation": "\"ตอบ ระยะสั้น ครับ\"" },
  { "id": 96, "category": "เทคโนโลยีสารสนเทศ", "question": "ข้อใดคือ Software?", "options": ["Monitor", "RAM", "CPU", "Photoshop"], "answerIndex": 3, "explanation": "\"ตอบ Photoshop ครับ\"" },
  { "id": 97, "category": "เทคโนโลยีสารสนเทศ", "question": ".docx เป็นไฟล์ของโปรแกรมใด?", "options": ["Word", "Excel", "Notepad", "PowerPoint"], "answerIndex": 0, "explanation": "\"ตอบ Microsoft Word ครับ\"" },
  { "id": 98, "category": "เทคโนโลยีสารสนเทศ", "question": "Social ใดเน้นการสมัครงาน?", "options": ["Facebook", "Instagram", "LinkedIn", "TikTok"], "answerIndex": 2, "explanation": "\"ตอบ LinkedIn ครับ\"" },
  { "id": 99, "category": "เทคโนโลยีสารสนเทศ", "question": "ISP คืออะไร?", "options": ["คนเล่นเน็ต", "ผู้ให้บริการอินเทอร์เน็ต", "ช่างซ่อมคอม", "สายเคเบิล"], "answerIndex": 1, "explanation": "\"ตอบ ผู้ให้บริการอินเทอร์เน็ต ครับ\"" },
  { "id": 100, "category": "เทคโนโลยีสารสนเทศ", "question": "Cookie ในเว็บไซต์คืออะไร?", "options": ["ขนม", "ไฟล์เก็บข้อมูลผู้ใช้", "ไวรัส", "โฆษณา"], "answerIndex": 1, "explanation": "\"ตอบ ไฟล์เก็บข้อมูลพฤติกรรมผู้ใช้ครับ\"" },
  { "id": 101, "category": "เทคโนโลยีสารสนเทศ", "question": "มารยาทเน็ตเรียกว่า?", "options": ["Netiquette", "Law", "Rule", "Security"], "answerIndex": 0, "explanation": "\"ตอบ Netiquette ครับ\"" },
  { "id": 102, "category": "เทคโนโลยีสารสนเทศ", "question": "HTTP คืออะไร?", "options": ["ที่อยู่เว็บ", "โปรโตคอลสื่อสารเว็บ", "ความเร็วเน็ต", "ชื่อคอม"], "answerIndex": 1, "explanation": "\"ตอบ โปรโตคอลหลักในการส่งข้อมูลเว็บครับ\"" },
  { "id": 103, "category": "เทคโนโลยีสารสนเทศ", "question": "Malware คืออะไร?", "options": ["ซอฟต์แวร์ดี", "ซอฟต์แวร์ประสงค์ร้าย", "ฮาร์ดแวร์ใหม่", "ความปลอดภัย"], "answerIndex": 1, "explanation": "\"ตอบ ซอฟต์แวร์ประสงค์ร้ายครับ\"" },
  { "id": 104, "category": "เทคโนโลยีสารสนเทศ", "question": "Download คืออะไร?", "options": ["ส่งไฟล์ไปเน็ต", "ดึงไฟล์จากเน็ตลงเครื่อง", "ลบไฟล์", "ย้ายไฟล์"], "answerIndex": 1, "explanation": "\"ตอบ การดึงไฟล์จากเน็ตลงเครื่องเราครับ\"" },
  { "id": 105, "category": "เทคโนโลยีสารสนเทศ", "question": "ปุ่ม Print Screen มีไว้ทำอะไร?", "options": ["พิมพ์งาน", "ถ่ายภาพหน้าจอ", "ปิดจอ", "เพิ่มแสง"], "answerIndex": 1, "explanation": "\"ตอบ ถ่ายภาพหน้าจอครับ\"" },
  { "id": 106, "category": "เทคโนโลยีสารสนเทศ", "question": "Two-Factor Authentication มีไว้เพื่อ?", "options": ["ความเร็ว", "ความปลอดภัย 2 ชั้น", "ประหยัดเน็ต", "ใช้ง่าย"], "answerIndex": 1, "explanation": "\"ตอบ การยืนยันตัวตน 2 ชั้นครับ\"" },
  { "id": 107, "category": "เทคโนโลยีสารสนเทศ", "question": "ปุ่ม Ctrl + Z คืออะไร?", "options": ["Copy", "Paste", "Undo", "Redo"], "answerIndex": 2, "explanation": "\"ตอบ Undo ย้อนกลับคำสั่งล่าสุดครับ\"" },
  { "id": 108, "category": "เทคโนโลยีสารสนเทศ", "question": "IoT ย่อมาจาก?", "options": ["Internet of Things", "Input of Time", "Internal of Tech", "Identity of Tool"], "answerIndex": 0, "explanation": "\"ตอบ Internet of Things ครับ\"" },
  { "id": 109, "category": "เทคโนโลยีสารสนเทศ", "question": "Captcha มีไว้ทำอะไร?", "options": ["สวยงาม", "แยกคนกับบอต", "เพิ่มความเร็ว", "แจกรางวัล"], "answerIndex": 1, "explanation": "\"ตอบ เพื่อตรวจสอบว่าเป็นมนุษย์จริงๆ ครับ\"" },
  { "id": 110, "category": "เทคโนโลยีสารสนเทศ", "question": "ไฟล์รูปภาพยอดนิยมบนเว็บคือนามสกุลใด?", "options": ["txt", "mp3", "jpg", "exe"], "answerIndex": 2, "explanation": "\"ตอบ jpg ครับ\"" },

  // --- หมวดที่ 5: กฎหมายที่ประชาชนควรรู้ (ข้อ 111-130) ---
  { "id": 111, "category": "กฎหมาย", "question": "จดทะเบียนสมรสได้เมื่ออายุเท่าใด?", "options": ["15", "17", "18", "20"], "answerIndex": 1, "explanation": "\"ตอบ 17 ปีบริบูรณ์ครับ\"" },
  { "id": 112, "category": "กฎหมาย", "question": "ต้องมีบัตรประชาชนครั้งแรกเมื่ออายุเท่าใด?", "options": ["7", "15", "17", "20"], "answerIndex": 0, "explanation": "\"ตอบ 7 ปีบริบูรณ์ครับ\"" },
  { "id": 113, "category": "กฎหมาย", "question": "คนไร้ความสามารถทำนิติกรรมผลเป็นอย่างไร?", "options": ["สมบูรณ์", "โมฆะ", "โมฆียะ", "ใช้ได้"], "answerIndex": 1, "explanation": "\"ตอบ โมฆะ ครับ\"" },
  { "id": 114, "category": "กฎหมาย", "question": "การทำร้ายร่างกายผู้อื่นเป็นความผิดอาญาหรือไม่?", "options": ["ไม่ผิด", "ผิด", "ผิดเฉพาะแพ่ง", "ผิดเฉพาะปกครอง"], "answerIndex": 1, "explanation": "\"ตอบ ผิดกฎหมายอาญาครับ\"" },
  { "id": 115, "category": "กฎหมาย", "question": "ขับรถฝ่าไฟแดงผิด พ.ร.บ. ใด?", "options": ["แพ่ง", "จราจรทางบก", "ป่าไม้", "รัฐธรรมนูญ"], "answerIndex": 1, "explanation": "\"ตอบ พ.ร.บ.จราจรทางบก ครับ\"" },
  { "id": 116, "category": "กฎหมาย", "question": "พินัยกรรมแบบธรรมดาต้องมีพยานกี่คน?", "options": ["ไม่ต้องมี", "1", "2", "3"], "answerIndex": 2, "explanation": "\"ตอบ 2 คนครับ\"" },
  { "id": 117, "category": "กฎหมาย", "question": "ชิงทรัพย์ต่างจากลักทรัพย์อย่างไร?", "options": ["เอาของคนอื่น", "ใช้กำลังประทุษร้าย", "ทำตอนกลางคืน", "ทำคนเดียว"], "answerIndex": 1, "explanation": "\"ตอบ ชิงทรัพย์คือลักทรัพย์โดยใช้กำลังครับ\"" },
  { "id": 118, "category": "กฎหมาย", "question": "ศาลสูงสุดของไทยในระบบศาลยุติธรรมคือ?", "options": ["ชั้นต้น", "อุทธรณ์", "ฎีกา", "รัฐธรรมนูญ"], "answerIndex": 2, "explanation": "\"ตอบ ศาลฎีกา ครับ\"" },
  { "id": 119, "category": "กฎหมาย", "question": "กฎหมายที่สภาออกให้เรียกว่า?", "options": ["พ.ร.บ.", "พ.ร.ก.", "พ.ร.ฎ.", "กฎกระทรวง"], "answerIndex": 0, "explanation": "\"ตอบ พระราชบัญญัติ (พ.ร.บ.) ครับ\"" },
  { "id": 120, "category": "กฎหมาย", "question": "วิ่งราวทรัพย์ คืออะไร?", "options": ["แอบหยิบ", "ฉกฉวยต่อหน้า", "ขู่เข็ญ", "งัดบ้าน"], "answerIndex": 1, "explanation": "\"ตอบ ฉกฉวยเอาไปซึ่งหน้าครับ\"" },
  { "id": 121, "category": "กฎหมาย", "question": "อายุความคดีลักทรัพย์กี่ปี?", "options": ["5", "10", "15", "20"], "answerIndex": 1, "explanation": "\"ตอบ 10 ปี ครับ\"" },
  { "id": 122, "category": "กฎหมาย", "question": "แจ้งความคดียอมความได้ภายในกี่เดือน?", "options": ["1", "3", "6", "12"], "answerIndex": 1, "explanation": "\"ตอบ 3 เดือนนับแต่รู้เรื่องและรู้ตัวผู้ทำผิดครับ\"" },
  { "id": 123, "category": "กฎหมาย", "question": "กฎหมายที่รัฐมนตรีออกคือ?", "options": ["พ.ร.บ.", "เทศบัญญัติ", "กฎกระทรวง", "พ.ร.ฎ."], "answerIndex": 2, "explanation": "\"ตอบ กฎกระทรวง ครับ\"" },
  { "id": 124, "category": "กฎหมาย", "question": "การหมั้นสมบูรณ์เมื่อใด?", "options": ["ตกลงกัน", "ทำสัญญา", "ส่งมอบของหมั้น", "จดทะเบียน"], "answerIndex": 2, "explanation": "\"ตอบ เมื่อส่งมอบของหมั้นครับ\"" },
  { "id": 125, "category": "กฎหมาย", "question": "นิติกรรมที่ฝ่าฝืนกฎหมายชัดแจ้งผลเป็นอย่างไร?", "options": ["โมฆะ", "โมฆียะ", "สมบูรณ์", "รอยืนยัน"], "answerIndex": 0, "explanation": "\"ตอบ โมฆะ ครับ\"" },
  { "id": 126, "category": "กฎหมาย", "question": "ทายาทโดยธรรมลำดับที่ 1 คือ?", "options": ["พ่อแม่", "คู่สมรส", "ลูก", "พี่น้อง"], "answerIndex": 2, "explanation": "\"ตอบ ผู้สืบสันดาน (ลูก) ครับ\"" },
  { "id": 127, "category": "กฎหมาย", "question": "ดูหมิ่นซึ่งหน้าเป็นความผิดระดับใด?", "options": ["อาญาแผ่นดิน", "ยอมความได้", "ลหุโทษ", "ไม่ผิด"], "answerIndex": 2, "explanation": "\"ตอบ ลหุโทษ ครับ\"" },
  { "id": 128, "category": "กฎหมาย", "question": "สัญญาเกิดเมื่อใด?", "options": ["คิดในใจ", "เสนอและสนองตรงกัน", "มีพยาน 10 คน", "ไปหาตำรวจ"], "answerIndex": 1, "explanation": "\"ตอบ เมื่อคำเสนอและคำสนองตรงกันครับ\"" },
  { "id": 129, "category": "กฎหมาย", "question": "ทำร้ายผู้อื่นสาหัสยอมความได้หรือไม่?", "options": ["ได้", "ไม่ได้", "แล้วแต่เงิน", "แล้วแต่คนเจ็บ"], "answerIndex": 1, "explanation": "\"ตอบ ไม่ได้ครับ เป็นอาญาแผ่นดิน\"" },
  { "id": 130, "category": "กฎหมาย", "question": "ศาลที่พิจารณาคดีวินัยข้าราชการคือ?", "options": ["ศาลแขวง", "ศาลปกครอง", "ศาลจังหวัด", "ศาลฎีกา"], "answerIndex": 1, "explanation": "\"ตอบ ศาลปกครอง ครับ\"" },

  // --- หมวดที่ 6: สังคม วัฒนธรรม อาเซียน (ข้อ 131-150) ---
  { "id": 131, "category": "สังคม", "question": "ศาสนาพุทธนิกายหลักในไทยคือ?", "options": ["มหายาน", "เถรวาท", "เซ็น", "วัชรยาน"], "answerIndex": 1, "explanation": "\"ตอบ เถรวาท ครับ\"" },
  { "id": 132, "category": "สังคม", "question": "วันอาสาฬหบูชาเกี่ยวข้องกับเหตุการณ์ใด?", "options": ["เกิดพระธรรม", "เกิดพระสงฆ์องค์แรก", "ตรัสรู้", "ปรินิพพาน"], "answerIndex": 1, "explanation": "\"ตอบ เกิดพระสงฆ์องค์แรกครับ\"" },
  { "id": 133, "category": "สังคม", "question": "วัฒนธรรมด้านจิตใจเรียกว่า?", "options": ["คติธรรม", "เนติธรรม", "สหธรรม", "วัตถุธรรม"], "answerIndex": 0, "explanation": "\"ตอบ คติธรรม ครับ\"" },
  { "id": 134, "category": "สังคม", "question": "เวียนเทียนวันใดบ้าง?", "options": ["มาฆะ/วิสาขะ/อาสาฬหะ", "เข้าพรรษา", "ออกพรรษา", "สงกรานต์"], "answerIndex": 0, "explanation": "\"ตอบ มาฆะ วิสาขะ และอาสาฬหบูชาครับ\"" },
  { "id": 135, "category": "สังคม", "question": "จารีตคืออะไร?", "options": ["กฎหมาย", "ศีลธรรมที่ยึดถือเคร่งครัด", "แฟชั่น", "ระเบียบ"], "answerIndex": 1, "explanation": "\"ตอบ ศีลธรรมที่สังคมยึดถือเคร่งครัดครับ\"" },
  { "id": 136, "category": "สังคม", "question": "สีขาวในธงชาติไทยคือ?", "options": ["กษัตริย์", "ศาสนา", "ชาติ", "สันติภาพ"], "answerIndex": 1, "explanation": "\"ตอบ ศาสนา ครับ\"" },
  { "id": 137, "category": "สังคม", "question": "ค่านิยม 12 ประการ ข้อ 3 คือเรื่องใด?", "options": ["รักชาติ", "กตัญญู", "มีศีล", "ขยัน"], "answerIndex": 1, "explanation": "\"ตอบ กตัญญูต่อพ่อแม่ผู้ปกครองครูบาอาจารย์ครับ\"" },
  { "id": 138, "category": "สังคม", "question": "ประเพณีภาคเหนือคือ?", "options": ["ผีตาโขน", "ยี่เป็ง", "วิ่งควาย", "แห่เทียน"], "answerIndex": 1, "explanation": "\"ตอบ ยี่เป็ง ครับ\"" },
  { "id": 139, "category": "สังคม", "question": "เบญจธรรมคู่กับศีลข้อ 1 คือ?", "options": ["เมตตากรุณา", "สัมมาอาชีวะ", "กามสังวร", "สัจจะ"], "answerIndex": 0, "explanation": "\"ตอบ เมตตากรุณา ครับ\"" },
  { "id": 140, "category": "สังคม", "question": "ทฤษฎีใหม่แบ่งที่ดินอย่างไร?", "options": ["30:30:30:10", "25:25:25:25", "40:30:20:10", "50:20:20:10"], "answerIndex": 0, "explanation": "\"ตอบ 30:30:30:10 (น้ำ:นา:สวน:บ้าน) ครับ\"" },
  { "id": 141, "category": "อาเซียน", "question": "ประเทศใดไม่มีทางออกสู่ทะเล?", "options": ["ไทย", "ลาว", "เวียดนาม", "พม่า"], "answerIndex": 1, "explanation": "\"ตอบ ลาว ครับ\"" },
  { "id": 142, "category": "อาเซียน", "question": "รวงข้าว 10 รวงในตราอาเซียนหมายถึง?", "options": ["ความรวย", "ความสามัคคี 10 ประเทศ", "อาหาร", "ความเก่าแก่"], "answerIndex": 1, "explanation": "\"ตอบ ความสามัคคีของ 10 ประเทศสมาชิกครับ\"" },
  { "id": 143, "category": "อาเซียน", "question": "เขตการค้าเสรีอาเซียนเรียกว่า?", "options": ["AFTA", "APEC", "WTO", "WHO"], "answerIndex": 0, "explanation": "\"ตอบ AFTA ครับ\"" },
  { "id": 144, "category": "อาเซียน", "question": "ดอกไม้ประจำชาติลาวคือ?", "options": ["จำปาลาว", "กุหลาบ", "ชบา", "กล้วยไม้"], "answerIndex": 0, "explanation": "\"ตอบ ดอกจำปาลาว (ลีลาวดี) ครับ\"" },
  { "id": 145, "category": "อาเซียน", "question": "ASCC คือเสาหลักอาเซียนด้านใด?", "options": ["การเมือง", "เศรษฐกิจ", "สังคมและวัฒนธรรม", "การทหาร"], "answerIndex": 2, "explanation": "\"ตอบ สังคมและวัฒนธรรม ครับ\"" },
  { "id": 146, "category": "อาเซียน", "question": "เลขาธิการอาเซียนวาระกี่ปี?", "options": ["2", "4", "5", "6"], "answerIndex": 2, "explanation": "\"ตอบ 5 ปี และเป็นได้วาระเดียวครับ\"" },
  { "id": 147, "category": "อาเซียน", "question": "ภาษากลางอาเซียนคือ?", "options": ["ไทย", "จีน", "อังกฤษ", "มาเลย์"], "answerIndex": 2, "explanation": "\"ตอบ ภาษาอังกฤษ ครับ\"" },
  { "id": 148, "category": "อาเซียน", "question": "บรูไนปกครองระบอบใด?", "options": ["สมบูรณาญาสิทธิราชย์", "ประชาธิปไตย", "คอมมิวนิสต์", "สังคมนิยม"], "answerIndex": 0, "explanation": "\"ตอบ สมบูรณาญาสิทธิราชย์ ครับ\"" },
  { "id": 149, "category": "อาเซียน", "question": "เงินพม่าคือ?", "options": ["กีบ", "จ๊าด", "ดอง", "ริงกิต"], "answerIndex": 1, "explanation": "\"ตอบ จ๊าด ครับ\"" },
  { "id": 150, "category": "อาเซียน", "question": "สัตว์ประจำชาติไทยคือ?", "options": ["เสือ", "แมว", "ช้าง", "ไก่"], "answerIndex": 2, "explanation": "\"ตอบ ช้าง ครับ\"" }
]
